framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER)%'
        headers:
            from: '%env(string:APP_NAME)% <%env(MAILER_SENDER)%>'
