monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: grouped
            # Exclude Not Found & Not Allowed Method
            excluded_http_codes: [404, 405]
            # How many messages should be saved? Prevent memory leaks
            buffer_size: 50
            channels: ["!event", "!deprecation"]
        grouped:
            type: group
            members: [streamed, deduplicated]
        streamed:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.info.log"
            level: info
            # max number of log files to keep, defaults to zero, which means infinite files
            max_files: 10
        deduplicated:
            type: deduplication
            # the time in seconds during which duplicate entries are discarded (default: 60)
            time: 30
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: '%env(string:APP_NAME)% <%env(string:MAILER_SENDER)%>'
            to_email: ['dev.linkweb@gmail.com']
            subject: 'Error 500 occurred'
            # 500 errors are logged at the critical level
            level: critical
            formatter: monolog.formatter.html
            content_type: text/html
        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine" ]
